### ISSUE TITLE
gluster cluster from docker-compose file

### ISSUE THREAD

**Issue by IvanBiv** [gluster/gluster-containers#77]
We need deploy Gluster cluster thought docker-compose.yml file.
Our docker-compose file:
```
version: '3.6'
services:
    gfs:
        image: gluster/gluster-centos
        networks:
          - gfsnet
#        privileged: true
#        volumes:
#            - /home/glusterfs/data:/var/lib/glusterd:rw
#            - /home/glusterfs/volume:/data:rw
#            - /home/glusterfs/logs:/var/log/glusterfs:rw
#            - /home/glusterfs/conf:/etc/glusterfs:rw
#            - /dev:/dev:rw
#            - /etc/hosts:/etc/hosts:rw
        deploy:
            mode: global
            restart_policy:
                condition: on-failure

networks:
  gfsnet:
    attachable: true
```
I see next:
```
ivan@ivan1 /media/docker_compose/gluster $ sudo docker exec -it c3e69a4fcb7f bash
[root@c3e69a4fcb7f /]# ps aux |grep glusterd
root        24  0.0  0.0  12488  2180 pts/0    S+   19:09   0:00 grep --color=auto glusterd
[root@c3e69a4fcb7f /]# gluster peer status
Connection failed. Please check if gluster daemon is operational.
peer status: failed
[root@c3e69a4fcb7f /]# gluster --version
glusterfs 3.13.2
Repository revision: git://git.gluster.org/glusterfs.git
Copyright (c) 2006-2016 Red Hat, Inc. <https://www.gluster.org/>
GlusterFS comes with ABSOLUTELY NO WARRANTY.
It is licensed to you under your choice of the GNU Lesser
General Public License, version 3 or any later version (LGPLv3
or later), or the GNU General Public License, version 2 (GPLv2),
in all cases as published by the Free Software Foundation.
```

How we should to use docker-compose file for deploy Gluster cluster?
